services:
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth
    ports:
      - "5433:5432"

  catalog_db:
    image: postgres:15
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog
    ports:
      - "5434:5432"

  inventory_db:
    image: postgres:15
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory
    ports:
      - "5435:5432"

  orders_db:
    image: postgres:15
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_pass
      POSTGRES_DB: orders
    ports:
      - "5436:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5055:80"
    depends_on:
      - auth_db
      - catalog_db
      - inventory_db
      - orders_db
